### ISSUE TITLE
Getting an error trying to publish a package

### ISSUE THREAD

**Issue by homanchou** [hexpm/hexpm#1230]
```
mix hex.publish
Building elixir_xml_to_map 3.1.0
  Dependencies:
    erlsom ~> 1.4 (app: erlsom)
  App: elixir_xml_to_map
  Name: elixir_xml_to_map
  Files:
    lib
    lib/elixir_xml_to_map.ex
    lib/xml_to_map
    lib/xml_to_map/naive_map.ex
    lib/xml_to_map/nested_map.ex
    .formatter.exs
    mix.exs
    README.md
    LICENSE
  Version: 3.1.0
  Build tools: mix
  Description: A module for converting an XML string to a map
  Licenses: Apache-2.0
  Links:
    GitHub: https://github.com/homanchou/elixir-xml-to-map
  Elixir: ~> 1.9
Before publishing, please read the Code of Conduct: https://hex.pm/policies/codeofconduct

Publishing package to public repository hexpm.

Proceed? [Yn] Y
Building docs...
** (ArgumentError) unknown application: :hex
    (elixir 1.15.5) lib/application.ex:1010: Application.app_dir/1
    (elixir 1.15.5) lib/application.ex:1037: Application.app_dir/2
    (ex_doc 0.21.3) lib/ex_doc/formatter/html/autolink.ex:623: ExDoc.Formatter.HTML.Autolink.hex_lib_dirs/0
    (ex_doc 0.21.3) lib/ex_doc/formatter/html/autolink.ex:549: ExDoc.Formatter.HTML.Autolink.default_lib_dirs/1
    (ex_doc 0.21.3) lib/ex_doc/formatter/html/autolink.ex:546: ExDoc.Formatter.HTML.Autolink.default_lib_dirs/0
    (ex_doc 0.21.3) lib/ex_doc/formatter/html/autolink.ex:92: ExDoc.Formatter.HTML.Autolink.compile/3
    (ex_doc 0.21.3) lib/ex_doc/formatter/html.ex:68: ExDoc.Formatter.HTML.autolink_and_render/4
    (ex_doc 0.21.3) lib/ex_doc/formatter/html.ex:21: ExDoc.Formatter.HTML.run/2
```

```
elixir -v
Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.15.5 (compiled with Erlang/OTP 26)
```

Any suggestions?

**Comment by wojtekmach** [comment]
Could you update ExDoc just in case and try again?

**Comment by ericmj** [comment]
Closing due to lack of response.
