### ISSUE TITLE
:socket_closed_remotely when trying to get dependencies

### ISSUE THREAD

**Issue by bitboxer** [hexpm/hexpm#576]
We are seeing this error when trying to load dependencies via hexpm since this morning:

```
Failed to fetch record for 'hexpm:wooga/private_package' from registry (using cache)
** (exit) exited in: GenServer.call(Hex.Registry.Server, {:versions, "hexpm:wooga", "sbs_client"}, 60000)
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in Hex.Registry.Server.missing_status?/1
            (hex) lib/hex/registry/server.ex:365: Hex.Registry.Server.missing_status?({:error, :socket_closed_remotely})
            (hex) lib/hex/registry/server.ex:355: Hex.Registry.Server.print_error/4
            (hex) lib/hex/registry/server.ex:343: Hex.Registry.Server.write_result/4
            (hex) lib/hex/registry/server.ex:196: Hex.Registry.Server.handle_info/2
            (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
            (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
            (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
    (elixir) lib/gen_server.ex:774: GenServer.call/3
    (hex) lib/hex/remote_converger.ex:261: Hex.RemoteConverger.check_dep/3
    (elixir) lib/enum.ex:681: anonymous fn/3 in Enum.each/2
    (stdlib) lists.erl:1263: :lists.foldl/3
    (elixir) lib/enum.ex:1828: Enum.each/2
    (hex) lib/hex/remote_converger.ex:39: Hex.RemoteConverger.converge/2
    (mix) lib/mix/dep/converger.ex:94: Mix.Dep.Converger.all/4
    (mix) lib/mix/dep/converger.ex:50: Mix.Dep.Converger.converge/4

14:42:23.624 [error] GenServer Hex.Registry.Server terminating
** (FunctionClauseError) no function clause matching in Hex.Registry.Server.missing_status?/1
    (hex) lib/hex/registry/server.ex:365: Hex.Registry.Server.missing_status?({:error, :socket_closed_remotely})
    (hex) lib/hex/registry/server.ex:355: Hex.Registry.Server.print_error/4
    (hex) lib/hex/registry/server.ex:343: Hex.Registry.Server.write_result/4
    (hex) lib/hex/registry/server.ex:196: Hex.Registry.Server.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

I have no idea what is happening there, is this a problem on the hexpm servers or something we need to figure out on our side?

**Comment by ericmj** [comment]
We are tracking this issue here https://github.com/hexpm/hex/issues/428.
