### ISSUE TITLE
Failures on TravisCI: module :data_error is not available

### ISSUE THREAD

**Issue by tompave** [hexpm/hexpm#805]
Hello,

I'd like to report an issue that I've been observing on TravisCI for a couple of days. It might be caused by some network issues or corrupted response caching on Travis, but one of the errors suggests that some exception is not handled properly in the Hex client either, so that might something worth to flag.

The failures are related to either installing `hex` or running `mix deps.get`, and are happening in the build tasks for this PR: https://github.com/tompave/fun_with_flags/pull/45, consistently with OTP 21.2. The PR doesn't change any of the installed packages, not their locked versions. The CI tasks for the same `mix.lock` passed on master branch, admittedly a few days before I pushed the branch for the failing PR, and in fact I suspect that this is a transient issue, although I'm not sure on what's the cause.

Obviously I've restarted the build several times, always getting the same errors, although on different build tasks (the build matrix is fairly complex).

## The failures

I've identified three different types of failure.

The first one, which seems to be caused by Hex: https://travis-ci.org/tompave/fun_with_flags/jobs/530539067

```
0.75s$ mix deps.get
12:30:46.600 [error] GenServer Hex.Registry.Server terminating
** (stop) :data_error
    :zlib.inflateEnd_nif(#Reference<0.1533087563.182321154.72562>)
    :zlib.gunzip/1
    (hex) lib/hex/registry/server.ex:355: Hex.Registry.Server.write_result/4
    (hex) lib/hex/registry/server.ex:228: Hex.Registry.Server.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3

Last message: {:get_package, .... (omitted for brevity)

** (UndefinedFunctionError) function :data_error.exception/1 is undefined (module :data_error is not available)
    :data_error.exception([])
    (hex) lib/hex/registry/server.ex:59: Hex.Registry.Server.versions/2
    (hex) lib/hex/remote_converger.ex:424: Hex.RemoteConverger.verify_dep/3
    (elixir) lib/enum.ex:771: anonymous fn/3 in Enum.each/2
    (stdlib) maps.erl:257: :maps.fold_1/3
    (elixir) lib/enum.ex:1941: Enum.each/2
    (hex) lib/hex/remote_converger.ex:40: Hex.RemoteConverger.converge/2
    (mix) lib/mix/dep/converger.ex:95: Mix.Dep.Converger.all/4
The command "mix deps.get" failed and exited with 1 during .
```

Then I have two other failures that are happening when running `mix local.hex --force`:

* https://travis-ci.org/tompave/fun_with_flags/jobs/530539053
```
$ mix local.hex --force
** (Mix) Could not install Hex because Mix could not verify authenticity of metadata file at "https://repo.hex.pm/installs/hex-1.x.csv". This may happen because a proxy or some entity is interfering with the download or because you don't have a public key to verify the download.
```

* https://travis-ci.org/tompave/fun_with_flags/jobs/530539074

```
$ mix local.hex --force
** (Mix) Data does not match the given SHA-512 checksum.
Expected: 376f3726ac104f7813824b2b49639bfa520114eac4499929321574039c540f8982de090f22b849fd9bc83ac52a8fb09de57d5465e06460e9e6b226ba54428b52
  Actual: aa224874e5adead11b48342d88194b54a5cc86832204b83eafc1b74e88264f79bb2103c758864eccb4b2f266e136aa754e20376b266edc81590b2046aadcd496
Could not run archive.install for:
    https://repo.hex.pm/installs/1.7.0/hex-0.19.0.ez
```

---

Do you have any suggestion on how to resolve them?

**Comment by ericmj** [comment]
The failed integrity and checksums check combined with the zlib data error suggests you get corrupted data. This would likely either be a bug in the HTTP client we are using or and issue on the CDN side.

Did you recently change OTP version? If it happens consistently for you can you try to to test with other OTP versions?
