### ISSUE TITLE
Cannot fetch dependencies from Hex, :honor_cipher_order error

### ISSUE THREAD

**Issue by dopatraman** [hexpm/hexpm#859]
When I run `mix deps.get` I get the following error for each dependency:
```
Failed to fetch record for 'hexpm/telemetry' from registry (using cache)
{:failed_connect, [{:to_address, {'repo.hex.pm', 443}}, {:inet, [:inet], {:option, :server_only, :honor_cipher_order}}]}
Failed to fetch record for 'hexpm/plug_cowboy' from registry (using cache)
{:failed_connect, [{:to_address, {'repo.hex.pm', 443}}, {:inet, [:inet], {:option, :server_only, :honor_cipher_order}}]}
Failed to fetch record for 'hexpm/plug' from registry (using cache)
{:failed_connect, [{:to_address, {'repo.hex.pm', 443}}, {:inet, [:inet], {:option, :server_only, :honor_cipher_order}}]}
Failed to fetch record for 'hexpm/ranch' from registry (using cache)
{:failed_connect, [{:to_address, {'repo.hex.pm', 443}}, {:inet, [:inet], {:option, :server_only, :honor_cipher_order}}]}
```
and so on. Is Hex down? Why can't I fetch anything?

Something that looks peculiar is this error:
```
* Getting telemetry (Hex package)
** (FunctionClauseError) no function clause matching in Regex.safe_run/3    
    
    The following arguments were given to Regex.safe_run/3:
    
        # 1
        ~r/\/\/([^:]*):[^@]+@/
    
        # 2
        "https://repo.hex.pm/tarballs/telemetry-0.4.0.tar"
    
        # 3
        [{:capture, :all, :index}, :global]
    
    Attempted function clauses (showing 1 out of 1):
    
        defp safe_run(%Regex{re_pattern: compiled, source: source, re_version: version}, string, options)
    
    (elixir) lib/regex.ex:463: Regex.safe_run/3
    (elixir) lib/regex.ex:663: Regex.do_replace/4
    (hex) lib/hex/scm.ex:103: Hex.SCM.update/1
    (hex) lib/hex/scm.ex:163: Hex.SCM.checkout/1
    (mix) lib/mix/dep/fetcher.ex:64: Mix.Dep.Fetcher.do_fetch/3
    (mix) lib/mix/dep/converger.ex:190: Mix.Dep.Converger.all/9
    (mix) lib/mix/dep/converger.ex:201: Mix.Dep.Converger.all/9
    (mix) lib/mix/dep/converger.ex:123: Mix.Dep.Converger.all/7
```
This looks related to the hex failure though (as it cannot fetch the telemetry library). What is doing on with Hex?

**Comment by wojtekmach** [comment]
As I mentioned in the other issue, you should be fine after updating Hex with `mix local.hex --force`, but let us know otherwise - in that case please attach output of `elixir --version` and `mix hex.info`.
