### ISSUE TITLE
mix fails to install dependencies

### ISSUE THREAD

**Issue by aarongraham** [hexpm/hexpm#900]
We just upgraded to the newest release (0.20.2) using `mix local.hex` and we are now unable to successfully complete a `mix deps.get` run and get the following error when we try. We have not yet tested to see if the install fails for every package or just some. 

```
** (KeyError) key :outer_checksum not found in: %{inner_checksum: "d8bd5404b73273989946e4f4f6d529e5c2088f5fa1ca790b4dbe81f4be408e61", managers: [:rebar], name: "neotoma", repo: "hexpm", version: "1.7.3"}. Did you mean one of:

      * :inner_checksum

    (hex) lib/hex/scm.ex:82: Hex.SCM.lock_status/6
    (hex) lib/hex/scm.ex:363: anonymous fn/2 in Hex.SCM.fetch_from_lock/1
    (elixir) lib/enum.ex:1053: anonymous fn/3 in Enum.flat_map/2
    (stdlib) maps.erl:232: :maps.fold_1/3
    (elixir) lib/enum.ex:1964: Enum.flat_map/2
    (hex) lib/hex/scm.ex:342: Hex.SCM.prefetch/1
    (hex) lib/hex/remote_converger.ex:56: Hex.RemoteConverger.converge/2
    (mix) lib/mix/dep/converger.ex:95: Mix.Dep.Converger.all/4
```

**Comment by desmondmonster** [comment]
we're seeing the same issue in other packages:
```
** (KeyError) key :outer_checksum not found in: %{inner_checksum: "38349f3e29aff4864352084fc736fa7fa0f2995a819a737554f7ebd28b85aaab", managers: [:mix], name: "elixir_make", repo: "hexpm", version: "0.6.0"}. Did you mean one of:

      * :inner_checksum

    (hex) lib/hex/scm.ex:82: Hex.SCM.lock_status/6
    (hex) lib/hex/scm.ex:363: anonymous fn/2 in Hex.SCM.fetch_from_lock/1
    (elixir) lib/enum.ex:1053: anonymous fn/3 in Enum.flat_map/2
    (stdlib) maps.erl:232: :maps.fold_1/3
    (elixir) lib/enum.ex:1964: Enum.flat_map/2
    (hex) lib/hex/scm.ex:342: Hex.SCM.prefetch/1
    (hex) lib/hex/remote_converger.ex:56: Hex.RemoteConverger.conve
```

**Comment by supersimple** [comment]
@aarongraham and @desmondmonster - first thing to try is `mix deps.clean --all`
